name: Apply terraform
description: Apply terraform module

inputs:
  ENVIRONMENT:
    required: true
    description: 'Which environment: dev, stg, prod'
  CLIENT:
    required: true
    description: 'Which client: default, agni ...'
  WORKING_DIR:
    required: true
    description: 'Which terraform root folder to work with'
  PROJECT_ID:
    required: true
    description: 'Google Cloud Project ID'
  GOOGLE_APPLICATION_CREDENTIALS:
    required: true
    description: 'Google Cloud Service Account Credentials'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
       
    - shell: bash
      id: init
      working-directory: ${{inputs.WORKING_DIR}}
      run: terraform init
#       run: terraform init -backend-config=./env/${{inputs.CLIENT}}-${{inputs.ENVIRONMENT}}/backend.tfvars -upgrade

    - shell: bash
      id: validate
      working-directory: ${{inputs.WORKING_DIR}}
      run: terraform validate

    - shell: bash
      id: apply
      working-directory: ${{inputs.WORKING_DIR}}
      run: terraform apply -var-file=./env/${{inputs.CLIENT}}-${{inputs.ENVIRONMENT}}/terraform.tfvars -auto-approve
